# syntax=docker/dockerfile:1

FROM golang:1.23

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/reference/dockerfile/#copy
COPY *.go ./
ENV SECRET_KEY="lab1"
ENV PORT=5000
ENV TOKEN_DURABILITY=420
# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /lab-1-provider

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/reference/dockerfile/#expose
EXPOSE 5000

# Run
CMD ["/lab-1-provider"]